services:
  - type: web
    name: interchange
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: COGNODB_USER
        value: cognodb
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_PASSWORD
        sync: false
